export const POSTS_LOADED = "POSTS_LOADED";
export const POST_LOADED = "POST_LOADED";
export const DATE_DIRECTION_CHANGED = "DATE_DIRECTION_CHANGED";
export const VIEWS_DIRECTION_CHANGED = "VIEWS_DIRECTION_CHANGED";